// ai-utils.js
// Real implementations using OpenAI Responses API + Structured Outputs

import OpenAI from "openai"

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
})

// Helper: call the model and force JSON matching a schema
async function aiJSON({ prompt, schema, temperature = 0.2, model = "gpt-5.1-mini" }) {
  const response = await openai.responses.create({
    model,
    input: prompt,
    temperature,
    response_format: {
      type: "json_schema",
      json_schema: {
        name: "strict_schema",
        schema,
        strict: true,
      },
    },
  })
  // SDK gives you a convenient string for the model's text output:
  const text = response.output_text
  return JSON.parse(text)
}

/**
 * generateQuiz(file)
 * - If `file` is provided, we read its text and ask the model to create a quiz from it.
 * - Otherwise, we return a small sample quiz generated by the model.
 */
export async function generateQuiz(file) {
  // Get file text (supports Browser File/Blob or raw string)
  let sourceText = ""
  if (file) {
    if (typeof file === "string") {
      sourceText = file
    } else if (typeof file?.text === "function") {
      sourceText = await file.text()
    } else if (file?.content) {
      sourceText = String(file.content)
    }
  }

  const schema = {
    type: "object",
    additionalProperties: false,
    required: ["title", "questions"],
    properties: {
      title: { type: "string" },
      questions: {
        type: "array",
        minItems: 2,
        items: {
          type: "object",
          additionalProperties: false,
          required: ["question", "options", "answer"],
          properties: {
            question: { type: "string" },
            options: {
              type: "array",
              items: { type: "string" },
              minItems: 2,
            },
            answer: { type: "string" },
          },
        },
      },
    },
  }

  const prompt = sourceText
    ? `Create a concise multiple-choice quiz from the following study material. 
Return JSON matching the schema. Keep questions unambiguous and factual.

Material:
---
${sourceText.slice(0, 30_000)}
---`
    : `Create a simple sample quiz about basic general knowledge. 
Return JSON matching the schema.`

  // Ask the model for structured JSON
  const quiz = await aiJSON({ prompt, schema })
  return quiz
}

/**
 * generateStudyPlan(topic, durationDays = 7)
 * - Builds a day-by-day plan with activities.
 */
export async function generateStudyPlan(topic, durationDays = 7) {
  const safeDays = Math.max(1, Math.min(60, Number(durationDays) || 7))

  const schema = {
    type: "array",
    minItems: safeDays,
    maxItems: safeDays,
    items: {
      type: "object",
      additionalProperties: false,
      required: ["topic", "activities"],
      properties: {
        topic: { type: "string" },
        activities: {
          type: "array",
          items: { type: "string" },
          minItems: 3,
        },
      },
    },
  }

  const prompt = `Create a ${safeDays}-day study plan for the topic: "${topic}".
Each day:
- Provide a focused subtopic (progressing from fundamentals to advanced).
- Include at least 3 concrete activities (e.g., read X, watch Y, do Z practice).
Return JSON matching the schema only.`

  const plan = await aiJSON({ prompt, schema })
  return plan
}

export default {
  generateQuiz,
  generateStudyPlan,
}




